// postgres database
version: '3.5'
services:
  db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
    postgres:
    pgadmin: